// Do not edit. This file is machine generated by the Resource DLL Wizard.

library GraphW;

{ITE} {RCFileType} {C\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\GraphW_DRC.rc}

{$R 'C\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\GraphW_DRC.res' 'C\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\GraphW_DRC.rc'}

{$E NOR}

begin
end.
